name: Build Executor Docker Image

on:
  push:
    tags:
      - 'executor_*'   # реагировать на теги, начинающиеся с executor_

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment variables
        run: |
          echo "DEV1C_EXECUTOR_API_KEY=${{ secrets.DEV1C_EXECUTOR_API_KEY }}" >> "$GITHUB_ENV"
          echo "DOCKER_REGISTRY_URL=${{ secrets.DOCKER_REGISTRY_URL }}" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: |
          export EXECUTOR_VERSION="${GITHUB_REF#refs/tags/executor_}"
          echo "Собираем executor версии ${EXECUTOR_VERSION}"
          ./scripts/prepare_executor_api_key.sh
          DOCKER_BUILDKIT=1 docker build \
            --secret id=dev1c_executor_api_key,src=/tmp/dev1c_executor_api_key.txt \
            --pull \
            --build-arg EXECUTOR_VERSION="$EXECUTOR_VERSION" \
            -t $DOCKER_REGISTRY_URL/executor:$EXECUTOR_VERSION \
            -f ./src/executor/Dockerfile \
            .
      - name: Test Docker image
        run: |
          export EXECUTOR_VERSION="${GITHUB_REF#refs/tags/executor_}"
          ./tests/test-executor.sh

      - name: Push Docker image
        run: |
          export EXECUTOR_VERSION="${GITHUB_REF#refs/tags/executor_}"
          docker push "${{ secrets.DOCKER_REGISTRY_URL }}/executor:${EXECUTOR_VERSION}"