name: Build vrunner2 Docker Image

on:
  push:
    tags:
      - 'vrunner2_*'   # реагировать на теги, начинающиеся с vrunner2_

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
      ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, test and push vrunner2 image
        run: |
          export ONEC_VERSION="${GITHUB_REF#refs/tags/vrunner2_}"
          echo "Собираем vrunner2 версии ${ONEC_VERSION}"
          ./src/build-vrunner2.sh
