name: Build Executor Docker Image

on:
  push:
    tags:
      - 'executor_*'   # реагировать на теги, начинающиеся с executor_

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, test and push
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DEV1C_EXECUTOR_API_KEY: ${{ secrets.DEV1C_EXECUTOR_API_KEY }}
        run: |
          export EXECUTOR_VERSION="${GITHUB_REF#refs/tags/executor_}"
          echo "Собираем executor версии ${EXECUTOR_VERSION}"
          ./src/build-executor.sh