name: Build Executor Docker Image

on:
  push:
    tags:
      - 'executor_*'   # реагировать на теги, начинающиеся с executor_

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set DEV1C_EXECUTOR_API_KEY env
        run: echo "DEV1C_EXECUTOR_API_KEY=${{ secrets.DEV1C_EXECUTOR_API_KEY }}" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: |
          export EXECUTOR_VERSION="${GITHUB_REF#refs/tags/executor_}"
          docker build \
            --build-arg "EXECUTOR_VERSION=$EXECUTOR_VERSION" \
            -t "${{ secrets.DOCKER_REGISTRY_URL }}/executor:${EXECUTOR_VERSION}" \
            -f ./src/executor/Dockerfile \
            .

      - name: Push Docker image
        run: |
          export EXECUTOR_VERSION="${GITHUB_REF#refs/tags/executor_}"
          docker push "${{ secrets.DOCKER_REGISTRY_URL }}/executor:${EXECUTOR_VERSION}"