name: CI Executor (build-only on PR)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/executor/**'
      - 'src/build-executor.sh'
      - 'tests/test-executor.sh'
      - 'scripts/**'
      - '.github/workflows/ci-executor.yml'

jobs:
  build-executor:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        executor_version: [ '3.0.2.2', '4.0.6.7', '5.2.6.3', '6.2.4.1', '7.0.3.3' ]
    env:
      PUSH_IMAGE: 'false'
      # опционально можно добавить усечённый SHA в тег, если понадобится хранить локально
      # CI_SUFFIX: -ci-${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Executor ${{ matrix.executor_version }} (no push)
        env:
          DEV1C_EXECUTOR_API_KEY: ${{ secrets.DEV1C_EXECUTOR_API_KEY }}
        run: |
          export EXECUTOR_VERSION="${{ matrix.executor_version }}"
          ./src/build-executor.sh
