name: CI onec-platform (dynamic by changed Dockerfiles)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/onec-platform/**'
      - 'src/vrunner/**'
      - 'src/build-onec-platform.sh'
      - 'src/build-vrunner.sh'
      - 'tests/test-onec-platform.sh'
      - 'tests/test-vrunner.sh'
      - 'scripts/**'
      - '.github/workflows/ci-onec-platform.yml'

jobs:
  detect:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      has_changes: ${{ steps.set-matrix.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            v8320: src/onec-platform/8.3.20.Dockerfile
            v8321: src/onec-platform/8.3.21.Dockerfile
            v8322: src/onec-platform/8.3.22.Dockerfile
            v8323: src/onec-platform/8.3.23.Dockerfile
            v8324: src/onec-platform/8.3.24.Dockerfile
            v8325: src/onec-platform/8.3.25.Dockerfile
            v8326: src/onec-platform/8.3.26.Dockerfile
            v8327: src/onec-platform/8.3.27.Dockerfile
            # common: любые изменения в workflow'ах, скриптах, тестах или утилитах
            common:
              - 'src/onec-platform/**'
              - 'src/vrunner/**'
              - 'src/build-onec-platform.sh'
              - 'src/build-vrunner.sh'
              - 'tests/test-onec-platform.sh'
              - 'tests/test-vrunner.sh'
              - 'scripts/**'
              - '.github/workflows/ci-onec-platform.yml'

      - id: set-matrix
        shell: bash
        run: |
          set -euo pipefail
          versions=()
          all_versions=( '8.3.20.2290' '8.3.21.1895' '8.3.22.2557' '8.3.23.2236' '8.3.24.1819' '8.3.25.1633' '8.3.26.1656' '8.3.27.1644' )
          [[ '${{ steps.changes.outputs.v8320 }}' == 'true' ]] && versions+=('8.3.20.2290')
          [[ '${{ steps.changes.outputs.v8321 }}' == 'true' ]] && versions+=('8.3.21.1895')
          [[ '${{ steps.changes.outputs.v8322 }}' == 'true' ]] && versions+=('8.3.22.2557')
          [[ '${{ steps.changes.outputs.v8323 }}' == 'true' ]] && versions+=('8.3.23.2236')
          [[ '${{ steps.changes.outputs.v8324 }}' == 'true' ]] && versions+=('8.3.24.1819')
          [[ '${{ steps.changes.outputs.v8325 }}' == 'true' ]] && versions+=('8.3.25.1633')
          [[ '${{ steps.changes.outputs.v8326 }}' == 'true' ]] && versions+=('8.3.26.1656')
          [[ '${{ steps.changes.outputs.v8327 }}' == 'true' ]] && versions+=('8.3.27.1644')

          # Если изменились общие файлы (workflow/scripts/tests/etc.), запустить сборку для всех версий
          if [[ '${{ steps.changes.outputs.common }}' == 'true' ]]; then
            versions=("${all_versions[@]}")
          fi

          if (( ${#versions[@]} == 0 )); then
            {
              printf '%s\n' 'has_changes=false'
              printf '%s\n' 'matrix={"onec_version":[]}'
            } >> "$GITHUB_OUTPUT"
          else
            printf '%s\n' 'has_changes=true' >> "$GITHUB_OUTPUT"
            json="$(jq -cn --argjson arr "$(printf '%s\n' "${versions[@]}" | jq -R . | jq -s .)" '{onec_version: $arr}')"
            printf '%s\n' "matrix=$json" >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: detect
    if: needs.detect.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.detect.outputs.matrix) }}

    env:
      ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
      ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
      DOCKER_REGISTRY_URL: 'local'
      PUSH_IMAGE: 'false'
      # опционально можно добавить усечённый SHA в тег, если понадобится хранить локально
      # CI_SUFFIX: -ci-${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build onec-platform ${{ matrix.onec_version }} (no push)
        run: |
          export ONEC_VERSION="${{ matrix.onec_version }}"
          ./src/build-onec-platform.sh
          ./src/build-vrunner.sh
